package com.seamless.bookkeeper.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "smart_rules",
    indices = [
        Index(value = ["merchant_name"]),
        Index(value = ["keyword"])
    ]
)
data class SmartRuleEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "merchant_name") val merchantName: String? = null,
    val keyword: String? = null,
    @ColumnInfo(name = "category_id") val categoryId: Long,
    @ColumnInfo(name = "account_id") val accountId: Long? = null,
    val confidence: Float = 1.0f,
    @ColumnInfo(name = "usage_count") val usageCount: Int = 0,
    @ColumnInfo(name = "is_auto_generated") val isAutoGenerated: Boolean = true,
    @ColumnInfo(name = "created_at") val createdAt: Long
)
