package com.seamless.bookkeeper.util

import com.seamless.bookkeeper.data.local.dao.SmartRuleDao
import com.seamless.bookkeeper.data.local.dao.TransactionDao
import com.seamless.bookkeeper.data.local.entity.SmartRuleEntity
import com.seamless.bookkeeper.domain.repository.TransactionRepository
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SmartLearningEngine @Inject constructor(
    private val smartRuleDao: SmartRuleDao,
    private val transactionRepository: TransactionRepository
) {
    suspend fun learnFromCorrection(merchantName: String?, newCategoryId: Long) {
        if (merchantName.isNullOrBlank()) return

        val existing = smartRuleDao.findByMerchant(merchantName)
        if (existing != null) {
            smartRuleDao.updateConfidence(existing.id, 1.0f)
            smartRuleDao.incrementUsageCount(existing.id)
        } else {
            smartRuleDao.insert(SmartRuleEntity(
                merchantName = merchantName,
                categoryId = newCategoryId,
                confidence = 1.0f,
                isAutoGenerated = false,
                createdAt = System.currentTimeMillis()
            ))
        }
    }
}
